config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :members, param: :slug do
    resources :attachments, only: %i[new create] do
      member do
        post :download
      end
    end
  end

  root to: 'members#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :member
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :attachments, dependent: :destroy

  validates 'name_zh-TW', presence: { message: '請填入名稱' }
  validates 'name_en', presence: { message: 'please fill in name' }

  before_create :set_slug

  private

  def set_slug
    self.slug = Digest::SHA2.hexdigest(Time.current.to_i.to_s).first(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    # 可以將 ["en", "zh-TW"] 設定為 VALID_LANG 放到 config/environment.rb 中
    if params[:locale] && I18n.available_locales.include?(params[:locale].to_sym)
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/attachments_controller.rb
require "google/cloud/storage"
require 'open-uri'
class AttachmentsController < ApplicationController
  before_action :find_member, only: %i[new create download]

  def new
    @attachment = @member.attachments.new
  end

  def create
    return redirect_to request.referer if params[:upload_file].blank?

    attachment = @member.attachments.new(
      file_name: file_name,
      storage_path: "upload_file/#{@member.name}/#{Time.current.to_i}_#{file_name}",
    )

    return render :new unless attachment.valid?

    bucket = find_bucket
    upload_result = bucket.create_file(params[:upload_file].path, attachment.storage_path)

    if upload_result && attachment.save!
      redirect_to members_path, notice: "已成功上傳 #{file_name}"
    else
      redirect_to members_path, notice: "上傳 #{file_name} 失敗，請再次上傳"
    end
  end

  def download
    attachment = @member.attachments.find(params[:id])
    bucket = find_bucket
    file = bucket.file(attachment.storage_path)
    file_data = open(file.signed_url).read
    send_data(file_data, filename: attachment.file_name)
  end

  private

  def find_member
    @member = Member.find_by(id: params[:member_id])
  end

  def file_name
    params[:upload_file].original_filename
  end

  def find_bucket
    storage = Google::Cloud::Storage.new(
      project_id: ENV['GOOGLE_CLOUD_PROJECT'],
      credentials: ENV['GOOGLE_CLOUD_CREDENTIALS']
    )
    storage.bucket ENV['MY_BUCKET']
  end
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  def index
    @members = Member.all
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def show
    @member = Member.find_by(slug: params[:slug])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to members_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit
    @member = Member.find_by(id: params[:id])
  end

  def update
    @member = Member.find_by(id: params[:id])

    if @member.update(member_params)
      redirect_to members_path, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @member = Member.find_by(id: params[:id])
    @member.destroy if @member
    redirect_to members_path, notice: "Member (#{@member.name}) 已刪除!"
  end

  private

  def member_params
    params.require(:member).permit('name_zh-TW', 'name_en')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attachments/new.html.erb
<h1>新增 attachment</h1>

<% if @attachment.errors.full_messages.present? %>
  <% @attachment.errors.full_messages.each do |error_message| %>
    <%= error_message %><br />
  <% end %>
<% end %>

<%= form_with(url: member_attachments_path(@attachment.member)) do |f| %>
  <%= f.label :upload_file, "上傳檔案" %><br/>
  <%= f.file_field :upload_file %><br/>

  <%= f.submit %>
<% end %>

<%= link_to '回 Member 列表', members_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GcpTrainingHomework</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div>
      <%= link_to I18n.t('chinese'), controller: controller_name, action: action_name, locale: "zh-TW" %>
      <%= link_to I18n.t('english'), controller: controller_name, action: action_name, locale: "en" %>
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<% if member.errors.full_messages.present? %>
  <% member.errors.full_messages.each do |error_message| %>
    <%= error_message %><br />
  <% end %>
<% end %>

<%= form_for(member) do |f| %>
  <%= f.label :name, I18n.t("activerecord.attributes.mameber.name_zh-TW") %>
  <%= f.text_field 'name_zh-TW' %> <br />
  <%= f.label :name, I18n.t("activerecord.attributes.mameber.name_en") %>
  <%= f.text_field 'name_en' %> <br />

  <%= f.submit %>
<% end %>

app/views/members/edit.html.erb
<h1>編輯 Member</h1>

<%= render "form", member: @member %>

<br />
<%= link_to '回 Member 列表', members_path %>

app/views/members/index.html.erb
<h1><%= I18n.t("activerecord.models.mameber") %></h1>

<% flash.each do |type, msg| %>
  <div> <%= msg %> </div>
<% end %>

<%= link_to I18n.t('new'), new_member_path %>

<hr>

<table>
  <thead>
    <tr>
      <td><%= I18n.t("activerecord.attributes.mameber.name_#{I18n.locale}") %></td>
      <td>Link</td>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
    <tr>
      <td><%= member.send("name_#{I18n.locale}") %></td>
      <td><%= link_to 'show_link', member_path(slug: member.slug) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/members/new.html.erb
<h1><%= I18n.t('new') %><%= I18n.t("activerecord.models.mameber") %></h1>

<%= render "form", member: @member %>

<br />
<%= link_to '回 Member 列表', members_path %>

app/views/members/show.html.erb
<h1><%= I18n.t('show') %><%= @member.send("name_#{I18n.locale}") %></h1>